"""Prompt construction for analytical query planning."""

from verisight.execution.formatting import QueryContextFormatter
from verisight.execution.planning import QueryRequest


class QueryPromptBuilder:
    """Build deterministic prompts for analytical SQL planning."""

    def __init__(self) -> None:
        self._context_formatter = QueryContextFormatter()

    def build(self, request: QueryRequest) -> str:
        """Build a planner prompt from an analytical query request."""

        context = self._context_formatter.format(request.context)

        return (
            "You are an analytical SQL planner for VeriSight.\n\n"
            "Generate exactly one read-only DuckDB SELECT query that answers "
            "the user's question using only the relations and columns provided "
            "below.\n\n"
            "Single-statement requirement:\n"
            "- Return exactly one SQL statement.\n"
            "- Never return multiple semicolon-separated SQL statements.\n"
            "- If the analytical question requires multiple related "
            "computations, comparisons, groupings, or intermediate results, "
            "combine them into one SQL statement when they can be represented "
            "without changing the meaning of the requested analysis.\n"
            "- Use CTEs, subqueries, conditional aggregation, window "
            "functions, joins, UNION, or UNION ALL within that single "
            "statement when analytically appropriate.\n"
            "- A WITH query containing one or more CTEs followed by one final "
            "SELECT is one SQL statement and is allowed.\n"
            "- UNION and UNION ALL may combine compatible result sets within "
            "the same SQL statement when doing so preserves clear and "
            "meaningful result semantics.\n"
            "- Do not emit separate SELECT statements for separate parts of "
            "the same analytical question.\n"
            "- Do not distort the requested analytical grain, aggregation, "
            "comparison, or interpretation merely to combine computations "
            "into one statement.\n"
            "- If one statement cannot meaningfully represent every possible "
            "interpretation of a broad question, generate the single "
            "analytical query that directly answers the evidence request "
            "expressed by the question without inventing additional "
            "semantics.\n\n"
            "Rules:\n"
            "- Return SQL only.\n"
            "- Do not include Markdown code fences.\n"
            "- Use only the provided relations and columns.\n"
            "- Do not access external files, URLs, environment variables, "
            "or external databases.\n"
            "- Do not use PRAGMA, ATTACH, DETACH, COPY, INSTALL, LOAD, "
            "EXPORT, SET, RESET, CALL, or VACUUM.\n"
            "- Do not modify data or database state.\n"
            "- Choose analytical operations according to the meaning of the "
            "question and the available evidence, not merely according to a "
            "column's physical or logical data type.\n"
            "- Determine the analytical grain required by the question before "
            "choosing SELECT expressions, aggregates, and GROUP BY columns.\n"
            "- When producing one result per entity, category, time period, "
            "or combination of dimensions, GROUP BY only the dimensions "
            "required to define that requested result grain.\n"
            "- Do not place an aggregated measure itself in GROUP BY merely "
            "to make the SQL valid. Doing so can collapse the aggregate back "
            "to row-level or measure-level values and misrepresent the "
            "requested analytical grain.\n"
            "- A column used as the argument of an aggregate such as SUM, "
            "AVG, MIN, or MAX should not also be a grouping key unless the "
            "question explicitly requires grouping by that same value and "
            "the resulting grain is analytically meaningful.\n"
            "- Do not mix row-level columns with grouped aggregate results "
            "unless those columns are legitimate grouping dimensions for the "
            "requested analytical grain.\n"
            "- If the question asks for an aggregate by particular "
            "dimensions, return the aggregate at that grain rather than "
            "including extra grouping columns that fragment the result into "
            "a finer grain.\n"
            "- Do not assume that a numeric column is additive merely because "
            "its values are numeric.\n"
            "- Use SUM only when the measure is supported as additive across "
            "the rows or groups being combined and summation answers the "
            "analytical question.\n"
            "- Do not sum a measure when doing so would produce a quantity "
            "with unsupported or unclear analytical meaning.\n"
            "- Use AVG only when an arithmetic mean is meaningful for the "
            "measure and the analytical question.\n"
            "- Do not assume that an unweighted average is equivalent to a "
            "weighted measure. Use a weighted calculation only when the "
            "required weighting quantities and their relationship to the "
            "measure are supported by the supplied data and question.\n"
            "- Consider other operations such as COUNT, COUNT DISTINCT, MIN, "
            "MAX, grouping, filtering, ordering, or returning unaggregated "
            "values when they better answer the analytical question.\n"
            "- Preserve the distinction between additive, non-additive, and "
            "semantically uncertain measures.\n"
            "- If the appropriate aggregation or interpretation of a measure "
            "is uncertain, prefer a conservative query that does not impose "
            "unsupported semantics.\n"
            "- Do not infer domain-specific meaning solely from a column name "
            "when the supplied context does not establish that meaning.\n"
            "- Do not invent semantic metadata, units, weighting rules, "
            "relationships, categories, hierarchies, or domain assumptions "
            "that are not supported by the supplied data and question.\n"
            "- Generate only the computation required to answer the question; "
            "do not add unrelated analytical assumptions.\n\n"
            "AVAILABLE DATA:\n"
            f"{context}\n\n"
            "QUESTION:\n"
            f"{request.question}\n"
        )
